[
 {
  "Error": {
   "Message": "ERRORED! Got Exception (if any): ERROR: Bot #0: Received invalid character 'Traceback (most recent call last):T'. (at character 1.)\nInput received from bot:\nTraceback (most recent call last):\n^; Response received (if any): Traceback (most recent call last):  File \"MyBotv2.py\", line 50, in <module>    logging.info(planet[0].owner)NameError: name 'planet' is not defined",
   "Turn": 1
  },
  "Frames": [
   {
    "Time": 32,
    "Turn": 0
   },
   {
    "Time": 56
   }
  ],
  "PlayerID": 0,
  "PlayerName": "STARTER"
 },
 {
  "Error": {},
  "Frames": [
   {
    "Time": 31,
    "Turn": 0
   },
   {
    "Commands": [
     {
      "angle": 283,
      "magnitude": 1,
      "owner": 1,
      "queue_number": 0,
      "shipId": 5,
      "type": "thrust"
     },
     {
      "angle": 285,
      "magnitude": 1,
      "owner": 1,
      "queue_number": 0,
      "shipId": 4,
      "type": "thrust"
     },
     {
      "angle": 284,
      "magnitude": 1,
      "owner": 1,
      "queue_number": 0,
      "shipId": 3,
      "type": "thrust"
     }
    ],
    "Planets": null,
    "Ships": [
     {
      "cooldown": 0,
      "docking": {
       "status": "undocked"
      },
      "health": 255,
      "id": 5,
      "owner": 1,
      "vel_x": 0.0,
      "vel_y": 0.0,
      "x": 120.22495105434386,
      "y": 122.02562993521477
     },
     {
      "cooldown": 0,
      "docking": {
       "status": "undocked"
      },
      "health": 255,
      "id": 4,
      "owner": 1,
      "vel_x": 0.0,
      "vel_y": 0.0,
      "x": 120.25881904510253,
      "y": 116.03407417371093
     },
     {
      "cooldown": 0,
      "docking": {
       "status": "undocked"
      },
      "health": 255,
      "id": 3,
      "owner": 1,
      "vel_x": 0.0,
      "vel_y": 0.0,
      "x": 120.24192189559967,
      "y": 119.02970427372401
     }
    ],
    "Time": 0,
    "Turn": 1
   }
  ],
  "PlayerID": 1,
  "PlayerName": "Settler"
 }
]
